# Change these first
owner: wbsnpc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: metatube
    url: https://javtube-acmecorporation.koyeb.app/
  


