# Change these first
owner: wbsnpc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: reader
    url: https://reading.npcssl.tk
  - name: 阅读
    url: https://reader.htmake.com/


